# discussions 触发以下操作 [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed] 时，生成文章并且发布至 Github Pages 和 Cloudflare Pages

name: Discussions Process Posts Deploy

on:
  discussion:
    types: [created, edited, deleted, pinned, unpinned, labeled, unlabeled, category_changed]

jobs:
  discussions-process-posts:
    name: Discussions Process Posts
    if: contains(fromJson('["q-a", "memo"]'), github.event.discussion.category.slug)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            args: [--frozen-lockfile]

      - name: setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: discussions process posts payload
        run: pnpm run discussions-process-posts "${{ github.event_path }}"

  deploy:
    name: Deploy
    needs: discussions-process-posts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy gitHub pages site
        id: deployment
        uses: actions/deploy-pages@v4
